
from openai import OpenAI

client = OpenAI(base_url="https://api.openai-proxy.org/v1",
                api_key="sk-WNnYtWWa5prkX9TjIE2W85jXKqrSVmEY5Nix4u345tncyoRl")  # 替换为你的API Key

def build_style_transfer_prompt(think_text):
    return f"""
You are refining explanations in a hateful speech detection dataset. The following <think>...</think> explanation was generated by a model, but the style is too segmented and rigid (e.g., bullet points, numbered analysis).

Your task is to rewrite the explanation into a more natural, paragraph-based reasoning style, similar to the sample provided below.

Keep the explanation inside <think> </think> tags. Do not change the meaning or conclusion—just rephrase and smooth the style.

Example:
"<think> The meme contains an image of a knight holding a sword, which historically can symbolize conflict or crusades. The text, \"it is time.. to send these parasites back to the desert,\" uses dehumanizing language by referring to a group as \"parasites.\" This term implies infestation and inferiority, seeking to degrade the targeted group. The phrase \"back to the desert\" suggests a focus on geographic origin, likely implying ethnicity, race, or nationality related to desert regions. These elements combined suggest a call for exclusion based on protected characteristics like race or ethnicity. </think>"

Now rewrite:
{think_text}
"""

def rewrite_think_style(raw_think):
    prompt = build_style_transfer_prompt(raw_think)
    
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[
            {"role": "system", "content": "You are a helpful AI that rewrites hateful speech detection explanations in a unified, clear style."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.3,
        max_tokens=800
    )
    
    return response.choices[0].message.content


import json

# 读取原始JSON文件
with open("/newdisk/public/wws/01-AIGC-GPRO/R1-V-main/sft_data_construct/gpt4o_hcd_sft_dataset_v3/merged_correct_samples-rewrite-28.json", 'r', encoding='utf-8') as f:
    data = json.load(f)

# 处理每个样本
for entry in data:
    old_think = entry["thinking"]
    new_think = rewrite_think_style(old_think)
    entry["thinking"] = new_think
    # break

# 保存处理后的JSON文件
with open("/newdisk/public/wws/01-AIGC-GPRO/R1-V-main/sft_data_construct/gpt4o_hcd_sft_dataset_v3/merged_correct_samples-rewrite-28-rewritten.json", 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)