compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: "cpu"  # 将优化器状态卸载到CPU
  offload_optimizer_config:
    device: "cpu"
    pin_memory: true  # 使用固定内存，提高CPU-GPU传输速度
    buffer_count: 5   # 缓冲区数量
    fast_init: true   # 快速初始化
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
